### ISSUE TITLE
How to get the authorization code on react native for the Facebook strategy

### ISSUE THREAD

**Issue by JackShannon** [pow-auth/assent#82]
I'm sorry, I know that this is not really directly related to assent.

The Facebook strategy requires an authorization code for the callback.

In this issue you say that "The Facebook strategy docs now highlights how to fetch the code client side to submit server side".

https://github.com/pow-auth/assent/issues/34#issuecomment-706741044

Our problem is that we are using https://github.com/facebook/react-native-fbsdk to implement the frontend facebook auth in react native. So we I don't think we can use the JS sdk to get the signed request and get the authorization code.

Please could you point me in the right direction on how to get the code from the accessToken in this situation?

**Comment by LukasKnuth** [comment]
I know this is a few years old but it can be hard to gauge how to do this with Assent.

It is my understanding that the Facebook Login SDK do **not give you access to the Authorization Code**. Instead, they return an _Access Token_ directly. You can work with this:

```elixir
def token_flow(access_token, _opts) do
  config = Keyword.merge(Facebook.default_config([]), strategy_config())
  token = %{"access_token" => access_token}
  with {:ok, user} <- Facebook.fetch_user(config, token) do
    config
    |> Facebook.normalize(user)
    |> extract_relevant()
  end
end
```

Note on security:

The `access_token` is opaque and can't be inspected by the server to verify if it was
actually created for the same Facebook Login App. Imagine the following attack scenario:

- A malicious actor sets up their own legit website "Cool Game" with Facebook Login
- A user of your "Jacks App" logs in on "Cool Game" using their Facebook account
- The malicious actor now has a valid `access_token` for that user
- The malicious actor sends the `access_token` meant for "Cool Game" to "Jacks App"
- They are logged in as the "Jacks App" user who actually just logged into "Cool Game"

There are two ways to prevent this attack on Facebook:

- [Inspect the Token using a debug API](https://developers.facebook.com/docs/facebook-login/security/#tokenhijacking)
- [Sending an `appsecret_proof` parameter](https://developers.facebook.com/docs/facebook-login/security/#proof)

Assent always sends the `appsecret_proof` parameter with the
`fetch_user/2` request. In the scenario above, the request to "Jacks App" fails because the
`access_token` that the malicious actor aquired is not linked to the same Facebook
Login Application than the secret the "Jacks App" server uses to generate the
`appsecret_proof` parameter.

**Comment by danschultzer** [comment]
Yeah, that's correct, with the native SDK it all happens client side. There isn't anything Assent really can give you because the whole OAuth 2.0 token exchange have already happened in the client. It's the same as this issue on Google integration in mobile apps: https://github.com/pow-auth/assent/issues/89

You'll have to handle the client <> backend integration yourself, i.e. send the access token (preferably encrypted) to the backend to then fetch the user calling `Assent.Strategy.Facebook.fetch_user(config, access_token)`. It'll also generate the appsecret proof as @LukasKnuth mentions.

We can add something in the docs for this, but it is a general problem with native integration where the OAuth flow happens in the client. If you have more control over it you can pass off the authorization params during the callback phase to the backend. But if you don't that control then Assent won't really have to do anything at all. It'll be up to the end-user to figure out how to integrate with their backend.
